package url.vista;

import javax.swing.JTable;

import url.modelo.Configuration;
import url.controlador.Control;

/**
 * @author Alberto J. Prieto Antunez
 * @version 17.01.2022
 */
public class DlgListOfTelescopes extends javax.swing.JDialog {

    /**
     * Creates new form dlgListOfTelescopes
     *
     */
    public Control ctrl;
    Configuration configuration;

    /**
     * This function launch the components of the DlgListOfTelescopes dialog.
     *
     * @param parent owner the {@code Frame} from which the dialog is displayed
     * @param modal specifies whether dialog blocks user input to other
     * top-level windows when shown. If {@code true}, the modality type property
     * is set to {@code DEFAULT_MODALITY_TYPE}, otherwise the dialog is
     * modeless.
     */
    public DlgListOfTelescopes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
    }

    /**
     * This function gets the list of telescopes from the JTable.
     *
     * @return JTable telescopes list.
     */
    public JTable getTblTelescopes() {
        return tblTelescopes;
    }

    /**
     * This function sets the controller of the system to DlgConfiguration.
     *
     * @param ctrl controller object.
     */
    public void setControlador(Control ctrl) {
        this.ctrl = ctrl;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgLaserSensitive = new javax.swing.ButtonGroup();
        btgLogData = new javax.swing.ButtonGroup();
        btgUpload = new javax.swing.ButtonGroup();
        pnlDatos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTelescopes = new javax.swing.JTable();
        tblTelescopes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("List of Telescopes");
        setSize(new java.awt.Dimension(1000, 1000));

        pnlDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("List of Telescopes"));

        tblTelescopes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Telescope Name", "FOV (deg)", "URL File Name", "Laser"
            }
        ));
        tblTelescopes.setAutoscrolls(false);
        tblTelescopes.setIntercellSpacing(new java.awt.Dimension(2, 2));
        tblTelescopes.setMaximumSize(new java.awt.Dimension(2147483647, 232323232));
        tblTelescopes.setMinimumSize(new java.awt.Dimension(100, 100));
        tblTelescopes.setRowHeight(24);
        jScrollPane1.setViewportView(tblTelescopes);

        tblTelescopes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Telescope Name", "FOV (deg)", "URL File Name", "Laser"
            }
        ));
        tblTelescopes.setAutoscrolls(false);
        tblTelescopes.setIntercellSpacing(new java.awt.Dimension(2, 2));
        tblTelescopes.setMaximumSize(new java.awt.Dimension(2147483647, 232323232));
        tblTelescopes.setMinimumSize(new java.awt.Dimension(100, 100));
        tblTelescopes.setRowHeight(24);
        jScrollPane1.setViewportView(tblTelescopes);

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgLaserSensitive;
    private javax.swing.ButtonGroup btgLogData;
    private javax.swing.ButtonGroup btgUpload;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JTable tblTelescopes;
    // End of variables declaration//GEN-END:variables

}
