package url.vista;

import javax.swing.DefaultComboBoxModel;

import url.modelo.Configuration;
import url.controlador.Control;

/**
 * @author Alberto J. Prieto Antunez
 * @version 17.01.2022
 */
public class DlgSetup extends javax.swing.JDialog {

    /**
     * Creates new form dlgSetup
     *
     */
    public Control ctrl;
    Configuration configuration;

    /**
     * This function launch the components of the DlgSetup dialog.
     *
     * @param parent owner the {@code Frame} from which the dialog is displayed
     * @param modal specifies whether dialog blocks user input to other
     * top-level windows when shown. If {@code true}, the modality type property
     * is set to {@code DEFAULT_MODALITY_TYPE}, otherwise the dialog is
     * modeless.
     */
    public DlgSetup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
    }

    /**
     * This function sets the controller of the system to DlgConfiguration.
     *
     * @param ctrl controller object.
     */
    public void setControlador(Control ctrl) {
        this.ctrl = ctrl;
    }

    /**
     * This function gets the telescopes list Combobox Model from the Combobox
     * of the DlgSetup screen.
     *
     * @return DefaultComboBoxModel.
     */
    public DefaultComboBoxModel getCbm() {
        return (DefaultComboBoxModel) this.cboTelescopes.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgLaserSensitive = new javax.swing.ButtonGroup();
        btgLogData = new javax.swing.ButtonGroup();
        btgUpload = new javax.swing.ButtonGroup();
        btgLaser = new javax.swing.ButtonGroup();
        pnlDatos = new javax.swing.JPanel();
        cboTelescopes = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTelescopeName = new javax.swing.JTextField();
        txtFov = new javax.swing.JTextField();
        txtOutputFile = new javax.swing.JTextField();
        btnYes = new javax.swing.JRadioButton();
        btnNo = new javax.swing.JRadioButton();
        btnClean = new javax.swing.JButton();
        pnlDatos1 = new javax.swing.JPanel();
        btnRemove = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Setup");
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 1000));

        pnlDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Setup"));

        cboTelescopes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTelescopesActionPerformed(evt);
            }
        });

        jLabel1.setText("Select a telescope:");

        jLabel2.setText("Telescope name:");

        jLabel3.setText("Field of view (degrees):");

        jLabel4.setText("Output file name (.dat):");

        jLabel5.setText("Is a laser-equipped telescope?");

        txtTelescopeName.setPreferredSize(new java.awt.Dimension(7, 22));

        txtFov.setPreferredSize(new java.awt.Dimension(7, 22));

        txtOutputFile.setPreferredSize(new java.awt.Dimension(7, 22));

        btgLaser.add(btnYes);
        btnYes.setText("Yes");

        btgLaser.add(btnNo);
        btnNo.setSelected(true);
        btnNo.setText("No");

        btnClean.setText("Clean");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelescopeName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOutputFile, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(cboTelescopes, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(btnYes)
                        .addGap(18, 18, 18)
                        .addComponent(btnNo))
                    .addComponent(txtFov, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTelescopes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnClean))
                .addGap(33, 33, 33)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtTelescopeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtOutputFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnYes)
                    .addComponent(btnNo))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlDatos1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDatos1.setMaximumSize(new java.awt.Dimension(32764, 32767));

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatos1Layout = new javax.swing.GroupLayout(pnlDatos1);
        pnlDatos1.setLayout(pnlDatos1Layout);
        pnlDatos1Layout.setHorizontalGroup(
            pnlDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatos1Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDatos1Layout.setVerticalGroup(
            pnlDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatos1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatos1Layout.createSequentialGroup()
                        .addGroup(pnlDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemove, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlDatos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlDatos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This function gets the telescope index from the Combobox when a telescope
     * is selected. This index is sent to the controller to write in every field
     * of the setup screen, the telescope data stored.
     *
     * @param evt event on select a telescope.
     */
    private void cboTelescopesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTelescopesActionPerformed
        int selectedIndex = this.cboTelescopes.getSelectedIndex();
        if (selectedIndex >= 0) {
            ctrl.loadTelescopeData(selectedIndex);
        }

    }//GEN-LAST:event_cboTelescopesActionPerformed

    /**
     * This function removes the telescope selected at the Combobox.
     *
     * @param evt event on click at the Remove button.
     */
    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        int selectedIndex = this.cboTelescopes.getSelectedIndex();
        ctrl.removeTel(selectedIndex);
    }//GEN-LAST:event_btnRemoveActionPerformed

    /**
     * This function clean all the text fields at the setup screen.
     *
     * @param evt event on click at the Clean button.
     */
    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        txtTelescopeName.setText("");
        txtFov.setText("");
        txtOutputFile.setText("");
        btnNo.doClick();
    }//GEN-LAST:event_btnCleanActionPerformed

    /**
     * This function save the data written at the text fields of the setup
     * screen for a telescope selected at the Combobox to save the new data.
     *
     * @param evt event on click at the Save button.
     */
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        int index = cboTelescopes.getSelectedIndex();
        boolean laser = btnYes.isSelected() ? true : false;
        ctrl.ModifyTelescope(index, this.cboTelescopes.getSelectedItem().toString(), this.txtTelescopeName.getText(), this.txtFov.getText(), this.txtOutputFile.getText(), laser);
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * This function Add a telescope to the system with the data set at the
     * setup screen.
     *
     * @param evt event on click at the Add button.
     */
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        boolean laser = btnYes.isSelected() ? true : false;
        ctrl.addTelescope(this.txtTelescopeName.getText(), this.txtFov.getText().replaceAll(" ", ""), this.txtOutputFile.getText(), laser);
    }//GEN-LAST:event_btnAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgLaser;
    private javax.swing.ButtonGroup btgLaserSensitive;
    private javax.swing.ButtonGroup btgLogData;
    private javax.swing.ButtonGroup btgUpload;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClean;
    public javax.swing.JRadioButton btnNo;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    public javax.swing.JRadioButton btnYes;
    public javax.swing.JComboBox<String> cboTelescopes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlDatos1;
    public javax.swing.JTextField txtFov;
    public javax.swing.JTextField txtOutputFile;
    public javax.swing.JTextField txtTelescopeName;
    // End of variables declaration//GEN-END:variables

}
