package url.vista;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import url.modelo.Configuration;
import url.controlador.Control;

import java.io.IOException;
import java.io.Serializable;
import java.io.UnsupportedEncodingException;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.crypto.IllegalBlockSizeException;

import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JRadioButton;
import javax.swing.Timer;

/**
 * @author Alberto J. Prieto Antunez
 * @version 17.01.2022
 */
public class DlgUrlData extends javax.swing.JDialog implements Serializable {

    /**
     * Creates new form dlgUrlData
     *
     */
    Timer t;
    Timer ttt;
    public Control ctrl;
    Configuration configuration;

    /**
     * This function launch the components of the DlgUrlData dialog.
     *
     * @param parent owner the {@code Frame} from which the dialog is displayed
     * @param modal specifies whether dialog blocks user input to other
     * top-level windows when shown. If {@code true}, the modality type property
     * is set to {@code DEFAULT_MODALITY_TYPE}, otherwise the dialog is
     * modeless.
     */
    public DlgUrlData(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
    }

    /**
     * This function sets the controller of the system to DlgConfiguration.
     *
     * @param ctrl controller object.
     */
    public void setControlador(Control ctrl) {
        this.ctrl = ctrl;
    }

    /**
     * This function gets the Combobox Model with the list of telescopes from
     * the URL screen.
     *
     * @return cboTelescope Combobox Model with the telescopes list.
     */
    public DefaultComboBoxModel getCbm() {
        return (DefaultComboBoxModel) this.cboTelescope.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgLaserSensitive = new javax.swing.ButtonGroup();
        btgLogData = new javax.swing.ButtonGroup();
        btgUpload = new javax.swing.ButtonGroup();
        btgLaserState = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        pnlDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRaHour = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cboTelescope = new javax.swing.JComboBox<>();
        txtRaMin = new javax.swing.JTextField();
        txtRaSec = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDecDeg = new javax.swing.JTextField();
        txtDecMin = new javax.swing.JTextField();
        txtDecSec = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEquinox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFov = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jrbLaserSensitiveYes = new javax.swing.JRadioButton();
        jrbLaserSensitiveNo = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jrbLogDataOn = new javax.swing.JRadioButton();
        jrbLogDataOff = new javax.swing.JRadioButton();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        lblUpdate = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblRaStatus = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblDecStatus = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblEquinoxStatus = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblFovStatus = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblLaserImpactedStatus = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblLogDataStatus = new javax.swing.JLabel();
        lblServerStatustxt = new javax.swing.JLabel();
        lblServerStatus = new javax.swing.JLabel();
        lblServerStatustxt1 = new javax.swing.JLabel();
        lblUploadFile = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jrbfileUploadON = new javax.swing.JRadioButton();
        jrbFileUploadOFF = new javax.swing.JRadioButton();
        lblUpdateServer1 = new javax.swing.JLabel();
        btnStartCoord = new javax.swing.JButton();
        btnStopCoord = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        lblAutoCoord = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblAutoCoordsStatus = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblLaserStateStatus = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jrbLaserStateOnSky = new javax.swing.JRadioButton();
        jrbLaserStateOn = new javax.swing.JRadioButton();
        jrbLaserStateOff = new javax.swing.JRadioButton();
        pnlBotones = new javax.swing.JPanel();
        btnSubmit = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("URL");
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 1000));

        pnlDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("URL File Generator"));

        jLabel1.setText("RA:");

        txtRaHour.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRaHour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRaHourMouseClicked(evt);
            }
        });
        txtRaHour.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRaHourKeyTyped(evt);
            }
        });

        jLabel3.setText("Telescope:");

        cboTelescope.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTelescopeActionPerformed(evt);
            }
        });

        txtRaMin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRaMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRaMinMouseClicked(evt);
            }
        });
        txtRaMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRaMinKeyTyped(evt);
            }
        });

        txtRaSec.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRaSec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRaSecMouseClicked(evt);
            }
        });
        txtRaSec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRaSecKeyTyped(evt);
            }
        });

        jLabel2.setText("DEC:");

        txtDecDeg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDecDeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDecDegMouseClicked(evt);
            }
        });
        txtDecDeg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDecDegKeyTyped(evt);
            }
        });

        txtDecMin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDecMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDecMinMouseClicked(evt);
            }
        });
        txtDecMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDecMinKeyTyped(evt);
            }
        });

        txtDecSec.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDecSec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDecSecMouseClicked(evt);
            }
        });
        txtDecSec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDecSecKeyTyped(evt);
            }
        });

        jLabel4.setText("Equinox (year):");

        txtEquinox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEquinox.setText("2000.0");
        txtEquinox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEquinoxKeyTyped(evt);
            }
        });

        jLabel6.setText("FOV (degrees):");

        txtFov.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFov.setText("0.2514");
        txtFov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFovKeyTyped(evt);
            }
        });

        jLabel7.setText("Laser Sensitive:");

        btgLaserSensitive.add(jrbLaserSensitiveYes);
        jrbLaserSensitiveYes.setText("YES");

        btgLaserSensitive.add(jrbLaserSensitiveNo);
        jrbLaserSensitiveNo.setSelected(true);
        jrbLaserSensitiveNo.setText("NO");

        jLabel8.setText("Log Data:");

        btgLogData.add(jrbLogDataOn);
        jrbLogDataOn.setSelected(true);
        jrbLogDataOn.setText("ON");

        btgLogData.add(jrbLogDataOff);
        jrbLogDataOff.setText("OFF");

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        lblUpdate.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblUpdate.setText("Last Update: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Semi-Automatic Mode");

        jLabel9.setText("Automatic Status:");

        lblStatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(204, 0, 0));
        lblStatus.setText("OFF");

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel10.setText("(HH MM SS.SS)");

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel11.setText("(DD MM SS.SS)");

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel12.setText("(e.g. 2000.0)");

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel13.setText("(e.g. 0.02345) ");

        jLabel14.setText("RA Status:");

        lblRaStatus.setText("Unknown");

        jLabel15.setText("DEC Status:");

        lblDecStatus.setText("Unknown");

        jLabel16.setText("Equinox Status:");

        lblEquinoxStatus.setText("Unknown");

        jLabel17.setText("FOV Status:");

        lblFovStatus.setText("Unknown");

        jLabel18.setText("Laser Sensitive:");

        lblLaserImpactedStatus.setText("Unknown");

        jLabel19.setText("Log Data:");

        lblLogDataStatus.setText("Unknown");

        lblServerStatustxt.setText("Status:");

        lblServerStatus.setText("Unknown");

        lblServerStatustxt1.setText("Upload File:");

        lblUploadFile.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUploadFile.setForeground(new java.awt.Color(204, 0, 0));
        lblUploadFile.setText("OFF");

        jLabel20.setText("Upload file to server:");

        btgUpload.add(jrbfileUploadON);
        jrbfileUploadON.setText("ON");
        jrbfileUploadON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbfileUploadONActionPerformed(evt);
            }
        });

        btgUpload.add(jrbFileUploadOFF);
        jrbFileUploadOFF.setSelected(true);
        jrbFileUploadOFF.setText("OFF");
        jrbFileUploadOFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFileUploadOFFActionPerformed(evt);
            }
        });

        lblUpdateServer1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblUpdateServer1.setText("Last Update to Sever: ");

        btnStartCoord.setText("Start");
        btnStartCoord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartCoordActionPerformed(evt);
            }
        });

        btnStopCoord.setText("Stop");
        btnStopCoord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopCoordActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Automatic Coordinates:");

        lblAutoCoord.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAutoCoord.setForeground(new java.awt.Color(204, 0, 0));
        lblAutoCoord.setText("OFF");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Coordinates Status:");

        lblAutoCoordsStatus.setText("Unknown");

        jLabel23.setText("Laser State:");

        lblLaserStateStatus.setText("Unknown");

        jLabel24.setText("Laser State:");

        btgLaserState.add(jrbLaserStateOnSky);
        jrbLaserStateOnSky.setText("ON-SKY");

        btgLaserState.add(jrbLaserStateOn);
        jrbLaserStateOn.setText("ON");

        btgLaserState.add(jrbLaserStateOff);
        jrbLaserStateOff.setSelected(true);
        jrbLaserStateOff.setText("OFF");

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAutoCoord, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlDatosLayout.createSequentialGroup()
                                            .addGap(50, 50, 50)
                                            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                                            .addGap(26, 26, 26)
                                            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))))
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addGap(38, 38, 38)
                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEquinox, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlDatosLayout.createSequentialGroup()
                                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtRaHour, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDecDeg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtDecMin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtRaMin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(4, 4, 4)
                                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtDecSec, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtRaSec, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnlDatosLayout.createSequentialGroup()
                                        .addComponent(txtFov, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cboTelescope, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlDatosLayout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(btnStartCoord)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnStopCoord))
                                    .addGroup(pnlDatosLayout.createSequentialGroup()
                                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jrbLaserStateOnSky, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDatosLayout.createSequentialGroup()
                                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jrbLaserSensitiveYes)
                                                    .addComponent(jrbLogDataOn)
                                                    .addComponent(jrbfileUploadON))
                                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(pnlDatosLayout.createSequentialGroup()
                                                        .addGap(32, 32, 32)
                                                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jrbLogDataOff)
                                                            .addComponent(jrbFileUploadOFF)))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jrbLaserStateOn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jrbLaserSensitiveNo))))))
                                        .addGap(13, 13, 13)
                                        .addComponent(jrbLaserStateOff))))
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(lblAutoCoordsStatus)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addGroup(pnlDatosLayout.createSequentialGroup()
                                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblServerStatustxt)
                                            .addComponent(lblServerStatustxt1))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblServerStatus)
                                            .addComponent(lblUploadFile, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblUpdateServer1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addGap(82, 82, 82))
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlDatosLayout.createSequentialGroup()
                                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(23, 23, 23)
                                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblDecStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(pnlDatosLayout.createSequentialGroup()
                                                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(lblEquinoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lblRaStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lblFovStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lblLaserImpactedStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lblLogDataStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lblLaserStateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(0, 0, Short.MAX_VALUE))))
                                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(pnlDatosLayout.createSequentialGroup()
                                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 46, Short.MAX_VALUE)))
                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnStart)
                                    .addComponent(btnStop))
                                .addGap(25, 25, 25))))))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStartCoord)
                            .addComponent(btnStopCoord)
                            .addComponent(jLabel21)
                            .addComponent(lblAutoCoord))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAutoCoordsStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboTelescope, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRaHour, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRaSec, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRaMin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDecDeg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDecSec, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDecMin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEquinox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFov, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbLaserSensitiveYes)
                            .addComponent(jrbLaserSensitiveNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jrbLaserStateOnSky)
                                .addComponent(jrbLaserStateOn)
                                .addComponent(jrbLaserStateOff)))
                        .addGap(13, 13, 13)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbLogDataOn)
                            .addComponent(jrbLogDataOff))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbfileUploadON)
                            .addComponent(jrbFileUploadOFF)))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addComponent(lblUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(lblStatus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(lblRaStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE))
                                .addGap(8, 8, 8)
                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(lblDecStatus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(lblEquinoxStatus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(lblFovStatus)))
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(btnStart)
                                .addGap(22, 22, 22)
                                .addComponent(btnStop)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLaserImpactedStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLaserStateStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLogDataStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUpdateServer1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblServerStatustxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUploadFile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblServerStatustxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblServerStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pnlBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        btnSubmit.setText("Submit");
        btnSubmit.setPreferredSize(new java.awt.Dimension(100, 30));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        pnlBotones.add(btnSubmit);

        btnClean.setText("Clean");
        btnClean.setPreferredSize(new java.awt.Dimension(100, 30));
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });
        pnlBotones.add(btnClean);

        btnClose.setText("Close");
        btnClose.setPreferredSize(new java.awt.Dimension(100, 30));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        pnlBotones.add(btnClose);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
            .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This function Close the URL screen when the Close button is clicked and
     * the action is confirmed.
     *
     * @param evt event on click on the Close button.
     */
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:

        int resultado = JOptionPane.showConfirmDialog(this, "Are you sure you want to close this window?", "Information", JOptionPane.YES_NO_OPTION);
        if (resultado == JOptionPane.YES_OPTION) {
            dispose();
            try {
                t.stop();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * This function submit the input data set in the URL screen and, if the
     * input is OK, writes the URL file with the format required by the LTCS. If
     * the upload to server is allowed, this send the URL data to the LTCS
     * server at the path specified at the configuration screen.
     *
     * @param evt event on click on the Submit button.
     */
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        int resultado = JOptionPane.showConfirmDialog(this, "Are you sure you want to submit?", "Information", JOptionPane.YES_NO_OPTION);
        if (resultado == JOptionPane.YES_OPTION) {
            JRadioButton selectedButton = null;
            if (jrbLaserSensitiveYes.isSelected()) {
                selectedButton = jrbLaserSensitiveYes;
            } else if (jrbLaserSensitiveNo.isSelected()) {
                selectedButton = jrbLaserSensitiveNo;
            }
            String laserSensitive = selectedButton.getText();

            JRadioButton selectedButton2 = null;
            if (jrbLogDataOn.isSelected()) {
                selectedButton2 = jrbLogDataOn;
            } else if (jrbLogDataOff.isSelected()) {
                selectedButton2 = jrbLogDataOff;
            }
            String logdata = selectedButton2.getText();

            JRadioButton selectedButton3 = null;
            if (jrbLaserStateOnSky.isSelected()) {
                selectedButton3 = jrbLaserStateOnSky;
            } else if (jrbLaserStateOn.isSelected()) {
                selectedButton3 = jrbLaserStateOn;
            } else if (jrbLaserStateOff.isSelected()) {
                selectedButton3 = jrbLaserStateOff;
            }
            String laserState = selectedButton3.getText();

            try {
                ctrl.createUrl(cboTelescope.getSelectedItem().toString(), txtRaHour.getText().replaceAll(" ", ""), txtRaMin.getText().replaceAll(" ", ""), txtRaSec.getText().replaceAll(" ", ""), txtDecDeg.getText().replaceAll(" ", ""), txtDecMin.getText().replaceAll(" ", ""), txtDecSec.getText().replaceAll(" ", ""), txtEquinox.getText().replaceAll(" ", ""), txtFov.getText().replaceAll(" ", ""), laserSensitive, laserState, logdata);
            } catch (IOException ex) {
                Logger.getLogger(DlgUrlData.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(DlgUrlData.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * This function clean the input data set in the RA and DEC text fields of
     * the URL screen.
     *
     * @param evt event on click on the Clean button.
     */
    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        // TODO add your handling code here:
        txtRaHour.setText("");
        txtRaMin.setText("");
        txtRaSec.setText("");
        txtDecDeg.setText("");
        txtDecMin.setText("");
        txtDecSec.setText("");

        // Set the focus on the RA hour text field.
        txtRaHour.requestFocus();
    }//GEN-LAST:event_btnCleanActionPerformed

    /**
     * This function set the URL file name with the telescope selected at the
     * Combobox from the URL screen and also change the field of view written at
     * that screen. After that, the configuration is updated with the new name
     * of the URL file.
     *
     * @param evt event on select on the telescope selected.
     */
    private void cboTelescopeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTelescopeActionPerformed
        if (cboTelescope.getSelectedIndex() >= 0) {
            ctrl.changeFileName();
            ctrl.changeFovField();
            try {
                ctrl.saveData();
            } catch (IOException | IllegalBlockSizeException ex) {
                Logger.getLogger(DlgUrlData.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cboTelescopeActionPerformed

    /**
     * This function limits to 3 characters the RA hours text field.
     *
     * @param evt event key typed.
     */
    private void txtRaHourKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRaHourKeyTyped
        if (txtRaHour.getText().length() >= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_txtRaHourKeyTyped

    /**
     * This function limits to 3 characters the RA minutes text field.
     *
     * @param evt event key typed.
     */
    private void txtRaMinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRaMinKeyTyped
        if (txtRaMin.getText().length() >= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_txtRaMinKeyTyped

    /**
     * This function limits to 6 characters the RA seconds text field.
     *
     * @param evt event key typed.
     */
    private void txtRaSecKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRaSecKeyTyped
        if (txtRaSec.getText().length() >= 6) {
            evt.consume();
        }
    }//GEN-LAST:event_txtRaSecKeyTyped

    /**
     * This function limits to 4 characters the DEC degrees text field.
     *
     * @param evt event key typed.
     */
    private void txtDecDegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDecDegKeyTyped
        if (txtDecDeg.getText().length() >= 4) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDecDegKeyTyped

    /**
     * This function limits to 3 characters the DEC minutes text field.
     *
     * @param evt event key typed.
     */
    private void txtDecMinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDecMinKeyTyped
        if (txtDecMin.getText().length() >= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDecMinKeyTyped

    /**
     * This function limits to 6 characters the DEC seconds text field.
     *
     * @param evt event key typed.
     */
    private void txtDecSecKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDecSecKeyTyped
        if (txtDecSec.getText().length() >= 6) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDecSecKeyTyped

    /**
     * This function limits to 9 characters the Equinox text field.
     *
     * @param evt event key typed.
     */
    private void txtEquinoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEquinoxKeyTyped
        if (txtEquinox.getText().length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEquinoxKeyTyped

    /**
     * This function limits to 12 characters the Field of View text field.
     *
     * @param evt event key typed.
     */
    private void txtFovKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFovKeyTyped
        if (txtFov.getText().length() >= 12) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFovKeyTyped

    /**
     * This function select all the text of the text field.
     *
     * @param evt event on click.
     */
    private void txtRaHourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRaHourMouseClicked
        txtRaHour.selectAll();
    }//GEN-LAST:event_txtRaHourMouseClicked

    /**
     * This function select all the text of the text field.
     *
     * @param evt event on click.
     */
    private void txtRaMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRaMinMouseClicked
        txtRaMin.selectAll();
    }//GEN-LAST:event_txtRaMinMouseClicked

    /**
     * This function select all the text of the text field.
     *
     * @param evt event on click.
     */
    private void txtRaSecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRaSecMouseClicked
        txtRaSec.selectAll();
    }//GEN-LAST:event_txtRaSecMouseClicked

    /**
     * This function select all the text of the text field.
     *
     * @param evt event on click.
     */
    private void txtDecDegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDecDegMouseClicked
        txtDecDeg.selectAll();
    }//GEN-LAST:event_txtDecDegMouseClicked

    /**
     * This function select all the text of the text field.
     *
     * @param evt event on click.
     */
    private void txtDecMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDecMinMouseClicked
        txtDecMin.selectAll();
    }//GEN-LAST:event_txtDecMinMouseClicked

    /**
     * This function select all the text of the text field.
     *
     * @param evt event on click.
     */
    private void txtDecSecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDecSecMouseClicked
        txtDecSec.selectAll();
    }//GEN-LAST:event_txtDecSecMouseClicked

    /**
     * This function active a Timer for the automation of the writting of the
     * URL file for the telescope selected at the Combobox. The time frecuency
     * is specified at the configuration screen (Semi-Automatic Mode). If the
     * uploading of the server is allowed, this also upload the URL file to the
     * server and path specified at the configuration screen.
     *
     * @param evt event on click on Start button.
     */
    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        lblStatus.setText("ON");
        lblStatus.setForeground(Color.GREEN.darker());
        System.out.println(ctrl.configTime());
        int timeFloat = (int) (ctrl.configTime() * 1000);
        t = new Timer(timeFloat, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                JRadioButton selectedButton = null;
                if (jrbLaserSensitiveYes.isSelected()) {
                    selectedButton = jrbLaserSensitiveYes;
                } else if (jrbLaserSensitiveNo.isSelected()) {
                    selectedButton = jrbLaserSensitiveNo;
                }
                String laserSensitive = selectedButton.getText();

                JRadioButton selectedButton2 = null;
                if (jrbLogDataOn.isSelected()) {
                    selectedButton2 = jrbLogDataOn;
                } else if (jrbLogDataOff.isSelected()) {
                    selectedButton2 = jrbLogDataOff;
                }
                String logdata = selectedButton2.getText();

                JRadioButton selectedButton3 = null;
                if (jrbLaserStateOnSky.isSelected()) {
                    selectedButton3 = jrbLaserStateOnSky;
                } else if (jrbLaserStateOn.isSelected()) {
                    selectedButton3 = jrbLaserStateOn;
                } else if (jrbLaserStateOff.isSelected()) {
                    selectedButton3 = jrbLaserStateOff;
                }
                String laserState = selectedButton3.getText();

                try {
                    System.out.println("Creating URL FILE");
                    ctrl.createUrl(cboTelescope.getSelectedItem().toString(), txtRaHour.getText().replaceAll(" ", ""), txtRaMin.getText().replaceAll(" ", ""), txtRaSec.getText().replaceAll(" ", ""), txtDecDeg.getText().replaceAll(" ", ""), txtDecMin.getText().replaceAll(" ", ""), txtDecSec.getText().replaceAll(" ", ""), txtEquinox.getText().replaceAll(" ", ""), txtFov.getText().replaceAll(" ", ""), laserSensitive, laserState, logdata);
                } catch (IOException ex) {
                    Logger.getLogger(DlgUrlData.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(DlgUrlData.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        t.start();
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * This function stops the Timer for the automation of the writting of the
     * URL file for the telescope selected at the Combobox.
     *
     * @param evt event on click on Stop button.
     */
    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        lblStatus.setText("OFF");
        lblStatus.setForeground(Color.RED);
        t.start();
        t.stop();
    }//GEN-LAST:event_btnStopActionPerformed

    /**
     * This function disables the uploads of the URL file to the server.
     *
     * @param evt event on click on the OFF JRbutton.
     */
    private void jrbFileUploadOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFileUploadOFFActionPerformed
        lblUploadFile.setText("OFF");
        lblUploadFile.setForeground(Color.RED);
    }//GEN-LAST:event_jrbFileUploadOFFActionPerformed

    /**
     * This function allow the uploads of the URL file to the server.
     *
     * @param evt event on click on the ON JRbutton.
     */
    private void jrbfileUploadONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbfileUploadONActionPerformed
        lblUploadFile.setText("ON");
        lblUploadFile.setForeground(Color.GREEN.darker());
    }//GEN-LAST:event_jrbfileUploadONActionPerformed

    /**
     * This function active a Timer for the automation of getting the
     * coordinates (RA, DEC) of the coordinates.txt file generated from the
     * telescope. This is for the full automation of the system. This function
     * gets the coordinates and writes into the URL screen and the URL file if
     * generated. The time of the updating frecuency of the coordinates read in
     * the file is set at the coordinates reading time at the configuration
     * screen. The path of the coordinates.txt file is specified at the
     * JFileChooser of the configuration screen.
     *
     * @param evt event on click on Start button.
     */
    private void btnStartCoordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartCoordActionPerformed
        lblAutoCoord.setText("ON");
        lblAutoCoord.setForeground(Color.GREEN.darker());
        int timeFloat2 = (int) (ctrl.configTime2() * 1000);
        ttt = new Timer(timeFloat2, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    System.out.println("Reading File");
                    ctrl.AutoCoord();
                } catch (UnsupportedEncodingException ex) {
                    //Logger.getLogger(DlgUrlData.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
        ttt.start();
    }//GEN-LAST:event_btnStartCoordActionPerformed

    /**
     * This function stops the Timer for the automation of getting the
     * coordinates (RA, DEC) of the coordinates.txt file generated from the
     * telescope.
     *
     * @param evt event on click on Stop button.
     */
    private void btnStopCoordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopCoordActionPerformed
        try {
            ttt.stop();
        } catch (Exception e) {
        }
        lblAutoCoord.setText("OFF");
        lblAutoCoord.setForeground(Color.RED);
    }//GEN-LAST:event_btnStopCoordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgLaserSensitive;
    private javax.swing.ButtonGroup btgLaserState;
    private javax.swing.ButtonGroup btgLogData;
    private javax.swing.ButtonGroup btgUpload;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStartCoord;
    public javax.swing.JButton btnStop;
    private javax.swing.JButton btnStopCoord;
    private javax.swing.JButton btnSubmit;
    public javax.swing.JComboBox<String> cboTelescope;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jrbFileUploadOFF;
    private javax.swing.JRadioButton jrbLaserSensitiveNo;
    private javax.swing.JRadioButton jrbLaserSensitiveYes;
    private javax.swing.JRadioButton jrbLaserStateOff;
    private javax.swing.JRadioButton jrbLaserStateOn;
    private javax.swing.JRadioButton jrbLaserStateOnSky;
    private javax.swing.JRadioButton jrbLogDataOff;
    private javax.swing.JRadioButton jrbLogDataOn;
    private javax.swing.JRadioButton jrbfileUploadON;
    public javax.swing.JLabel lblAutoCoord;
    public javax.swing.JLabel lblAutoCoordsStatus;
    public javax.swing.JLabel lblDecStatus;
    public javax.swing.JLabel lblEquinoxStatus;
    public javax.swing.JLabel lblFovStatus;
    public javax.swing.JLabel lblLaserImpactedStatus;
    public javax.swing.JLabel lblLaserStateStatus;
    public javax.swing.JLabel lblLogDataStatus;
    public javax.swing.JLabel lblRaStatus;
    public javax.swing.JLabel lblServerStatus;
    private javax.swing.JLabel lblServerStatustxt;
    private javax.swing.JLabel lblServerStatustxt1;
    private javax.swing.JLabel lblStatus;
    public javax.swing.JLabel lblUpdate;
    public javax.swing.JLabel lblUpdateServer1;
    public javax.swing.JLabel lblUploadFile;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDatos;
    public javax.swing.JTextField txtDecDeg;
    public javax.swing.JTextField txtDecMin;
    public javax.swing.JTextField txtDecSec;
    public javax.swing.JTextField txtEquinox;
    public javax.swing.JTextField txtFov;
    public javax.swing.JTextField txtRaHour;
    public javax.swing.JTextField txtRaMin;
    public javax.swing.JTextField txtRaSec;
    // End of variables declaration//GEN-END:variables

}
