package url.vista;

import javax.swing.JOptionPane;

import java.io.IOException;
import java.io.Serializable;

import java.util.logging.Level;
import java.util.logging.Logger;

import url.controlador.Control;
import url.modelo.Configuration;
import url.modelo.URL;

/**
 * @author Alberto J. Prieto Antunez
 * @version 17.01.2022
 */
public class FrmPrincipal extends javax.swing.JFrame implements Serializable {

    /**
     * Creates new form Frame Principal
     */
    Control ctrl;
    DlgUrlData dlgUrlData;
    Configuration configuration;
    URL url;

    /**
     * This function launch the components of the Frame Principal.
     *
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This function sets the controller of the system to DlgConfiguration.
     *
     * @param ctrl controller object.
     */
    public void setControlador(Control ctrl) {
        this.ctrl = ctrl;
    }

    /**
     * This function sets the configuration of the system to Frame Principal.
     *
     * @param configuration configuration object.
     */
    public void setClassConfiguration(Configuration configuration) {
        this.configuration = configuration;
    }

    /**
     * This function sets the URL Data Dialog of the system to Frame Principal.
     *
     * @param dlgUrlData URL Data Dialog.
     */
    public void setDlgUrlData(DlgUrlData dlgUrlData) {
        this.dlgUrlData = dlgUrlData;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniUrl = new javax.swing.JMenuItem();
        mniSalir = new javax.swing.JMenuItem();
        mnuTelescopes = new javax.swing.JMenu();
        mniListOfTelescopes = new javax.swing.JMenuItem();
        mniSetupTelescope = new javax.swing.JMenuItem();
        mnuOpciones = new javax.swing.JMenu();
        mniConfiguration = new javax.swing.JMenuItem();
        mniAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LTCS URL Generator");
        setName("frmPrincipal"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/url/imagenes/_MG_0996-CC.jpg"))); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Version 0.9.06 20220223 ");
        jLabel2.setMaximumSize(new java.awt.Dimension(0, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(0, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(29, 13));
        jPanel1.add(jLabel2, java.awt.BorderLayout.PAGE_END);

        mnuFile.setMnemonic('A');
        mnuFile.setText("   File   ");

        mniUrl.setText("   URL    ");
        mniUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUrlActionPerformed(evt);
            }
        });
        mnuFile.add(mniUrl);

        mniSalir.setText("   Exit   ");
        mniSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalirActionPerformed(evt);
            }
        });
        mnuFile.add(mniSalir);

        jMenuBar1.add(mnuFile);

        mnuTelescopes.setMnemonic('A');
        mnuTelescopes.setText(" Telescopes");

        mniListOfTelescopes.setText("   List of Telescopes");
        mniListOfTelescopes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniListOfTelescopesActionPerformed(evt);
            }
        });
        mnuTelescopes.add(mniListOfTelescopes);

        mniSetupTelescope.setText("   Setup");
        mniSetupTelescope.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSetupTelescopeActionPerformed(evt);
            }
        });
        mnuTelescopes.add(mniSetupTelescope);

        jMenuBar1.add(mnuTelescopes);

        mnuOpciones.setMnemonic('O');
        mnuOpciones.setText("   Options   ");

        mniConfiguration.setText("   Configuration   ");
        mniConfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConfigurationActionPerformed(evt);
            }
        });
        mnuOpciones.add(mniConfiguration);

        mniAbout.setText("   About");
        mniAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAboutActionPerformed(evt);
            }
        });
        mnuOpciones.add(mniAbout);

        jMenuBar1.add(mnuOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This function displays the URL Data screen in case of been cliked on the
     * menu.
     *
     * @param evt on click event.
     */
    private void mniUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUrlActionPerformed
        ctrl.mostrarDlgUrlData();
    }//GEN-LAST:event_mniUrlActionPerformed

    /**
     * This function displays the Configuration screen in case of been cliked on
     * the menu.
     *
     * @param evt on click event.
     */
    private void mniConfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConfigurationActionPerformed
        ctrl.mostrarDlgConfiguration();
    }//GEN-LAST:event_mniConfigurationActionPerformed

    /**
     * This function upload to the LTCS server, if allowed, a URL file with
     * Laser Sensitive NO. This is a safety action in case the operator forgets
     * to set the Laser Sensitive to NO when operation finishes.
     *
     * @param evt on Close Window event.
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            ctrl.createUrl(this.dlgUrlData.cboTelescope.getSelectedItem().toString(), "10", "00", "00", "28", "00", "00", "2000.0", "0.333", "NO", "OFF", "OFF");
            ctrl.saveListData();
        } catch (IOException ex) {
            Logger.getLogger(DlgUrlData.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * This function displays the About screen in case of been cliked on the
     * menu.
     *
     * @param evt on click event.
     */
    private void mniAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAboutActionPerformed
        ctrl.mostrarDlgAbout();
    }//GEN-LAST:event_mniAboutActionPerformed

    /**
     * This function displays the List of Telescopes screen in case of been
     * cliked on the menu.
     *
     * @param evt on click event.
     */
    private void mniListOfTelescopesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniListOfTelescopesActionPerformed
        ctrl.mostrarDlgListOfTelescopes();
    }//GEN-LAST:event_mniListOfTelescopesActionPerformed

    /**
     * This function upload to the LTCS server, if allowed, a URL file with
     * Laser Sensitive NO. This is a safety action in case the operator forgets
     * to set the Laser Sensitive to NO when operation finishes.
     *
     * @param evt on Close Window event.
     */
    private void mniSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalirActionPerformed
        int resultado = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Información", JOptionPane.YES_NO_OPTION);
        if (resultado == JOptionPane.YES_OPTION) {
            try {
                ctrl.createUrl(this.dlgUrlData.cboTelescope.getSelectedItem().toString(), "10", "00", "00", "28", "00", "00", "2000.0", "0.333", "NO", "OFF", "OFF");
                ctrl.saveListData();
            } catch (IOException ex) {
                Logger.getLogger(DlgUrlData.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            dispose();
        }
    }//GEN-LAST:event_mniSalirActionPerformed

    /**
     * This function displays the Setup screen in case of been cliked on the
     * menu.
     *
     * @param evt on click event.
     */
    private void mniSetupTelescopeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSetupTelescopeActionPerformed
        ctrl.mostrarDlgSetup();
    }//GEN-LAST:event_mniSetupTelescopeActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mniAbout;
    private javax.swing.JMenuItem mniConfiguration;
    private javax.swing.JMenuItem mniListOfTelescopes;
    private javax.swing.JMenuItem mniSalir;
    private javax.swing.JMenuItem mniSetupTelescope;
    private javax.swing.JMenuItem mniUrl;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuOpciones;
    private javax.swing.JMenu mnuTelescopes;
    // End of variables declaration//GEN-END:variables

}
